sql:
  users: sql/raw_data/users.sql
  distribution_centers: sql/raw_data/distribution_centers.sql
  inventory_items: sql/raw_data/inventory_items.sql
  products: sql/raw_data/products.sql
  orders: sql/raw_data/orders.sql
  order_items: sql/raw_data/order_items.sql
  events: sql/raw_data/events.sql

indexes:
  data_processing: sql/raw_data/indexes.sql
  # data_embedding: sql/embeddings/indexes.sql

order_lookback_days: 180 # 6 meses. Pedidos mais velhos que isso não são atualizados

embedding:
  embedding_model: all-MiniLM-L6-v2
  batch_size: 256
  device: "cpu"

metrics:
  returns_cost: 0.10 # 10% do custo da logística reversa em caso de devolução
  cohort_limit: 12 # 12 meses

rag_model: deepseek-r1:1.5b
